sudo: required
services:
    - docker

before_install:
    - docker build -t staskosatkin/docker-react -f dev.dockerfile .

script:
    - docker run -e CI=true staskosatkin/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-351045331751"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

language: generic
