sudo: required
services:
    - docker

before_install:
    - docker build -t staskosatkin/docker-react -f dev.dockerfile .

script:
    - docker run -e CI=true staskosatkin/docker-react npm run test -- --coverage

language: generic
