version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
    - "3000:3000"
    volumes:
    - /app/node_modules
    - .:/app
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: dev.dockerfile
    command: ["npm", "run", "test"]
    volumes:
      - /app/node_modules
      - .:/app
